### ISSUE TITLE
Not possible to set width smaller than 275 due to min width property

### ISSUE THREAD

**Issue by cramatt** [vime-js/vime#277]
The styling guide suggests is possible to set the width of the player like so:

```css
vm-player {
  --vm-settings-width: 100px;
}
```

But this is misleading because due to a min-width property the player can never be smaller than 275px wide. 
 
https://github.com/vime-js/vime/blob/1e8f386a46df47e7bcef408ceb5e116ca9a513e8/packages/core/src/components/core/player/player.css#L23

I tried a few ways to override this css property, for example

```css
.player {
    min-width: 100px !important!
}
```

But this did not seem to work which I suspect is due to the constructed stylesheet / shadow DOM usage. 

I am working in React. 

If this is a bug, please update the code to take the width property into effect when setting min-width. Otherwise, if I should be able to set the css using `.player` class or similar, please provide an example.
